#raspberry pi GPIO pin definitions

class GpioPins:
    LEFT_MOTOR_FORWARD = 7
    LEFT_MOTOR_BACKWARD = 11
    RIGHT_MOTOR_FORWARD = 13
    RIGHT_MOTOR_BACKWARD = 15
    ULTRASONIC_SENSOR_TRIG = 18
    ULTRASONIC_SENSOR_ECHO = 16
