#raspberry pi GPIO pin definitions
#using physical pin #'s, not GPIO #'s

class GpioPins:
    LEFT_MOTOR_FORWARD = 31
    LEFT_MOTOR_BACKWARD = 33
    RIGHT_MOTOR_FORWARD = 35
    RIGHT_MOTOR_BACKWARD = 37
    ULTRASONIC_SENSOR_TRIG = 7
    ULTRASONIC_SENSOR_ECHO = 12
    IR_SENSOR_LEFT = 24
    IR_SENSOR_RIGHT = 26
    SERVO_ULTRASONIC_SENSOR = 19
    SERVO_HORIZONTAL_CAMERA = 00
    SERVO_VERTICAL_CAMERA = 00

