#!/usr/bin/python -tt
import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)

LEFT_MOTOR_FORWARD=7
LEFT_MOTOR_BACKWARD=11
RIGHT_MOTOR_FORWARD=13
RIGHT_MOTOR_BACKWARD=15

GPIO.setup(LEFT_MOTOR_FORWARD, GPIO.OUT)
GPIO.setup(LEFT_MOTOR_BACKWARD, GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_FORWARD, GPIO.OUT)
GPIO.setup(RIGHT_MOTOR_BACKWARD, GPIO.OUT)

print "both motors forward"
GPIO.output(LEFT_MOTOR_FORWARD,1)
GPIO.output(LEFT_MOTOR_BACKWARD,0)
GPIO.output(RIGHT_MOTOR_FORWARD,1)
GPIO.output(RIGHT_MOTOR_BACKWARD,0)
time.sleep(2)
print "both motors stop"
GPIO.output(LEFT_MOTOR_FORWARD,0)
GPIO.output(LEFT_MOTOR_BACKWARD,0)
GPIO.output(RIGHT_MOTOR_FORWARD,0)
GPIO.output(RIGHT_MOTOR_BACKWARD,0)
time.sleep(2)
print "both motor backward"
GPIO.output(LEFT_MOTOR_FORWARD,0)
GPIO.output(LEFT_MOTOR_BACKWARD,1)
GPIO.output(RIGHT_MOTOR_FORWARD,0)
GPIO.output(RIGHT_MOTOR_BACKWARD,1)
time.sleep(5)
print "left motor forward"
GPIO.output(RIGHT_MOTOR_FORWARD,0)
GPIO.output(RIGHT_MOTOR_BACKWARD,0)
GPIO.output(LEFT_MOTOR_FORWARD,1)
GPIO.output(LEFT_MOTOR_BACKWARD,0)
time.sleep(2)

GPIO.cleanup()
